#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AFA.Android.Resource", IsApplication=true)]

namespace AFA.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int gray = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int green = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int lightgreen = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int pink = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int red = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int list_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sharkFin = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int AddressButton = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int Allies = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int CityState = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int CommentsButton = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int ContactLabel = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int DescriptionText = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int EditOrgButton = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int EmailButton = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int EventsButton = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int FollowingButton = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int NeedVolunteersLabel = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int NewsButton = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int OrgImage = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int OrgName = 2131099650;
			
			// aapt resource value: 0x7f060012
			public const int Organizations = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int PhoneButton = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int UniteButton = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int WebsiteButton = 2131099662;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Organization = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OrganizationListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Organizations = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
